### ISSUE TITLE
assignment 35 1B

### ISSUE THREAD

**Issue by DrM00G** [RileyPaddock/assignment_problems#1]
I'm pretty sure you over simplified what the probability is for each thing. It should be:
    #x | p(x)
    #0 | (1-λ)^4 
    #1 | 4λ(1-λ)^3
    #2 | 6λ^2(1-λ)^2
    #3 | 4λ^3(1-λ)
    #4 | λ^4

**Comment by RileyPaddock** [comment]
Resolved
