### ISSUE TITLE
Your plot function in euler_estimator.py is too long 

### ISSUE THREAD

**Issue by C0BBL3** [RileyPaddock/assignment_problems#2]
Your plot function in euler_estimator.py is too long, can you split it up into multiple functions or figure out a way to shorten it, for example, the length of my plot code is 12 lines, and I'm pretty sure u can shorten it from 40 dense lines.

**Comment by RileyPaddock** [comment]
Updated it to use a helper function to do all the steps and the plot function only organizes the data and plots it.
