### ISSUE TITLE
Don't use rounds in your code, only use them for printing stuff out so you don't see 1.00000000000000000007

### ISSUE THREAD

**Issue by C0BBL3** [RileyPaddock/assignment_problems#3]
Don't use rounds in your code, only use them for printing stuff out so you don't see 1.00000000000000000007, its fine if the computer sees it because it doesn't care what the number looks like, a number is a number, while to use the 19 other zeros and a 7 don't mean anything to us. An instance of you using rounds in your code for computing purposes is in step_forward when you round the derivative, this can be very bad if you have a very small precision and small changing derivative where the rounding would make the 1, 19 other zeros and a 7 make just a 1 where the test would fail.

**Comment by RileyPaddock** [comment]
Okay, I got rid of all the round usages in my code and will now only use them in print statements and tests
